doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                dql:
                    string_functions:
                        DATE: App\Utils\Doctrine\Query\Mysql\Date
                auto_mapping: true
                second_level_cache:
                    enabled: true
                    log_enabled: true
                metadata_cache_driver:
                    type: service
                    id: meta.snc.client
                query_cache_driver:
                    type: service
                    id: cache.snc.client
                result_cache_driver:
                    type: service
                    id: cache.snc.client
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
