framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    default_locale: en

    session:
        handler_id: snc_redis.session.handler
        gc_probability: 1
        gc_divisor: 100
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0

    php_errors:
        log: true

    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: snc_redis.cache
        prefix_seed: '%env(APP_NAME)%'

    router:
        strict_requirements: ~
        utf8: true

    validation:
        email_validation_mode: html5
