version: '3.7'
services:
    rss:
        build:
            context: .
            dockerfile: ./.docker/build.dockerfile
        container_name: rss
        volumes:
            - .:/var/www
            - cache:/var/www/var/cache
            - vendor:/var/www/vendor
            - composer:/root/.composer
        labels:
            - traefik.enable=true
            - traefik.backend=rss
            - traefik.docker.network=rss_traefik
        restart: on-failure
        networks:
            - rss_traefik
            - rss_backend
            - rss_app
        ports:
            - 9666:80
        depends_on:
            - rss_proxy
            - rss_maria
            - rss_sentinel_1
            - rss_sentinel_2
            - rss_redis_1
            - rss_redis_2
        environment:
            TZ: "Europe/Riga"
        command: ["./command.sh"]

    rss_maria:
        image: mariadb/server:latest
        container_name: rss_maria
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3308:3306
        volumes:
            - /var/lib/mysql
            - ./.docker/mariadb:/etc/mysql/mariadb.conf.d:ro
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_HOST=%
        restart: always
        networks:
            - rss_backend

    rss_proxy:
        image: traefik:latest
        container_name: rss_proxy
        command: --docker --docker.exposedbydefault=false
        ports:
            - 9000:80
        networks:
            - rss_traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.docker/traefik:/etc/traefik
        restart: always
        labels:
            - traefik.docker.network=rss_traefik
            - traefik.enable=true

    rss_redis_1:
        image: bitnami/redis:latest
        container_name: rss_redis_1
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - rss_app
            - rss_backend
        restart: always
    rss_sentinel_1:
        image: bitnami/redis-sentinel:latest
        container_name: rss_sentinel_1
        environment:
            - REDIS_MASTER_HOST=rss_redis_1
        ports:
            - 6666:26379
        networks:
            - rss_app
            - rss_backend
        restart: always
    rss_redis_2:
        image: bitnami/redis:latest
        container_name: rss_redis_2
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - rss_app
            - rss_backend
        restart: always
    rss_sentinel_2:
        image: bitnami/redis-sentinel:latest
        container_name: rss_sentinel_2
        environment:
            - REDIS_MASTER_HOST=rss_redis_2
        ports:
            - 6667:26379
        networks:
            - rss_app
            - rss_backend
        restart: always

networks:
    rss_traefik:
        name: rss_traefik
        ipam:
            config:
                - subnet: 172.66.66.0/24
    rss_backend:
        name: rss_backend
        ipam:
            config:
                - subnet: 172.66.67.0/24
    rss_app:
        name: rss_app
        driver: bridge
        ipam:
            config:
                - subnet: 172.66.68.0/24

volumes:
    cache:
    vendor:
    composer:
